baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My Massive 3000-Page Hugo Site"
theme = "hello-friend"
defaultContentLanguage = "en"

[params]
  dateformat = "2006-01-02"
  defaultTheme = "dark" 
  description = "A simple site for my project."

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1
